### ISSUE TITLE
Stress Testing[HELP][INFORMATION]

### ISSUE THREAD

**Issue by RollerIn** [radum/performance-testing-framework#5]
Hello,
can we use this to check stress testing on real browsers?

if I want write a js to navigate ,login ..traversing to different pages…where I can write and execute these scenarios.

Thanks IN Advance.

**Comment by radum** [comment]
Hello,

Depends. This repo is just the glue between various tools and nothing more. Sitespeed and WPT both support scripting to move around pages and execute js on tested pages. Use those tools to handle your requirements.

Hope this helps.
